# Generated by Django 2.2.8 on 2020-01-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
