# Generated by Django 2.2.8 on 2020-01-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('owner', models.IntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
