# Generated by Django 2.2.8 on 2020-01-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headhot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('own_vacancy', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyBack',
            fields=[
                ('vacancy_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='headhot.Vacancy')),
                ('vacancy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headhot.User')),
            ],
        ),
    ]
